name: ZMK KBD ZephyrBuild

on: 
  # commented `push` trigger to reduce unnecessary build
  # - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    uses: nxtkb/zmk/.github/workflows/build-user-config.yml@main
